server:
  port: 8081
  servelet:
    context-path: /api

spring:
  servlet:
      multipart:
       max-file-size: 100MB
       max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projectsapp
    username: root
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/app
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


jwt:
  auth:
    converter:
      resource-id: backend-client
      credentials:
        secret: utydj5ehdEOexWcLiwVr5t5eFwWJW04I
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG

#keycloak:
#  realm: app
#  auth-server-url:  http://localhost:8082
#  ssl-required: external
#  resource: backend-client
#  bearer-only: true
#  credentials:
#   secret: utydj5ehdEOexWcLiwVr5t5eFwWJW04I
#  use-resource-role-mappings: true

config:
  path:
    tmp: "src/main/resources/tmp/"
    videos: "src/main/resources/videos/"
    images: "src/main/resources/images/"
