server:
  port: 8081



spring:
  webflux:
    codec:
      max-in-memory-size: 100MB
  servlet:
      multipart:
       max-file-size: 100MB
       max-request-size: 100MB
       enabled: true
       file-size-threshold: 0
       location: /tmp
       resolve-lazily: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projectsapp
    username: root
    password: root
